---
# tasks file for justniffer
- name: Install necessary packages
  apt:
    name={{ item }}
    update_cache=yes
    cache_valid_time=86400
    install-recommends=no
    state=present
  with_items:
    - autoconf
    - automake
    - g++
    - libboost-dev
    - libboost-regex-dev
    - libboost-program-options-dev
    - libboost-iostreams-dev
    - libpcap-dev
    - libtool
    - make

- name: Add git group
  group: name=git state=present

- name: Create git location
  file:
    path=/var/git
    owner=root
    group=git
    mode=g+rwxs
    recurse=yes
    state=directory

- name: Clone necessary repositories
  git:
    repo={{ item.src }}
    dest={{ item.dest }}
    depth=1
    accept_hostkey=yes
    force=yes
  with_items:
    - src: https://github.com/onotelli/justniffer
      dest: /var/git/justniffer

- name: Configure justniffer
  shell: cd /var/git/justniffer && autoreconf --force --install 1>/dev/null && ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr/local 1>/dev/null

- name: Build and install justniffer
  shell: cd /var/git/justniffer && make 1>/dev/null && make install-strip 1>/dev/null
